# Generated by Django 5.0.6 on 2024-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooks',
            name='price',
            field=models.IntegerField(),
        ),
    ]
