# Generated by Django 5.0.6 on 2024-06-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_mybooks_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mybooks',
            new_name='Book',
        ),
    ]
